//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookwormApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BOOK()
        {
            this.BOOK_AUTHOR = new HashSet<BOOK_AUTHOR>();
            this.BOOK_CART = new HashSet<BOOK_CART>();
            this.BOOK_AUTHOR1 = new HashSet<BOOK_AUTHOR>();
            this.GENREs = new HashSet<GENRE>();
        }
    
        public int BookId { get; set; }
        public int PublisherId { get; set; }
        public Nullable<int> InventoryId { get; set; }
        public string Title { get; set; }
        public Nullable<int> Edition { get; set; }
        public Nullable<int> Rating { get; set; }
        public string Type { get; set; }
        public string Description { get; set; }
        public Nullable<int> ISBN { get; set; }
        public Nullable<System.DateTime> CopyRightDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOOK_AUTHOR> BOOK_AUTHOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOOK_CART> BOOK_CART { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOOK_AUTHOR> BOOK_AUTHOR1 { get; set; }
        public virtual PUBLISHER PUBLISHER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GENRE> GENREs { get; set; }
    }
}
