//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookwormApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CREDIT_CARD
    {
        public int CardId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string CardType { get; set; }
        public string CardNumber { get; set; }
        public string NameOnCard { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public int SecurityCode { get; set; }
    }
}
