//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookwormApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVOICE
    {
        public int InvoiceId { get; set; }
        public int CustomerId { get; set; }
        public int CartId { get; set; }
        public int BillingId { get; set; }
        public int ShippingId { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
        public Nullable<System.DateTime> DateOrder { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
    }
}
